export const under19Players = [
  {
    id: 1,
    firstName: "ABULLAHI",
    lastName: "MUHAMMAD",
    dateOfBirth: "2007-08-29",
    position: "Defender",
    pos: "CB",
    preferredFoot: "R",
    jerseyNumber: 15,
    height: "182.5",
    weight: "79",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 2,
    firstName: "BOLAJI",
    lastName: "AIGBE",
    dateOfBirth: "2007-05-06",
    position: "Defender",
    pos: "CB",
    preferredFoot: "L",
    jerseyNumber: 30,
    height: "191",
    weight: "70",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 3,
    firstName: "CHUKWUDI",
    lastName: "ISAAC",
    dateOfBirth: "2007-08-26",
    position: "Forward",
    pos: "FW",
    preferredFoot: "R",
    jerseyNumber: 20,
    height: "173.5",
    weight: "70",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 4,
    firstName: "DANIEL",
    lastName: "ARIERHI",
    dateOfBirth: "2008-08-22",
    position: "Forward",
    pos: "FW",
    preferredFoot: "R",
    jerseyNumber: 29,
    height: "175",
    weight: "64",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 5,
    firstName: "DANIEL",
    lastName: "AIYENUGBA",
    dateOfBirth: "2009-11-28",
    position: "Goalkeeper",
    pos: "GK",
    preferredFoot: "R",
    jerseyNumber: 49,
    height: "176.5",
    weight: "72",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 6,
    firstName: "FAVOUR",
    lastName: "APUTAZIEM",
    dateOfBirth: "2007-03-17",
    position: "Goalkeeper",
    pos: "GK",
    preferredFoot: "L",
    jerseyNumber: 1,
    height: "195",
    weight: "97",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 7,
    firstName: "HASSAN",
    lastName: "WAHAB",
    dateOfBirth: "2007-06-06",
    position: "Midfielder",
    pos: "CM",
    preferredFoot: "R",
    jerseyNumber: 21,
    height: "170",
    weight: "63",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 8,
    firstName: "KPAROBO",
    lastName: "ARIERHI",
    dateOfBirth: "2007-01-11",
    position: "Forward",
    pos: "ST",
    preferredFoot: "R",
    jerseyNumber: 9,
    height: "179",
    weight: "73",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 9,
    firstName: "MERVIELLE",
    lastName: "AKINOCHO",
    dateOfBirth: " ",
    position: "Forward",
    pos: "FW",
    preferredFoot: "R",
    jerseyNumber: 32,
    height: "186.5",
    weight: "78",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 10,
    firstName: "MUHAMMAD",
    lastName: "LADAN",
    dateOfBirth: "2006-11-2",
    position: "Defender",
    pos: "LB",
    preferredFoot: "L",
    jerseyNumber: 3,
    height: "167",
    weight: "58",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 11,
    firstName: "MUIZ",
    lastName: "OLADIMEJI",
    dateOfBirth: "2008-06-05",
    position: "Midfielder",
    pos: "CM",
    preferredFoot: "R",
    jerseyNumber: 17,
    height: "175",
    weight: "65",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 12,
    firstName: "MUSA",
    lastName: "ABDULLAHI",
    dateOfBirth: "2005-11-01",
    position: "Defender",
    pos: "DM",
    preferredFoot: "R",
    jerseyNumber: 4,
    height: "164",
    weight: "62",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 13,
    firstName: "MUYIDEEN",
    lastName: "OLUDE",
    dateOfBirth: "2007-06-04",
    position: "Forward",
    pos: "FW",
    preferredFoot: "R",
    jerseyNumber: 7,
    height: "169",
    weight: "55",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 14,
    firstName: "OKEMUTE",
    lastName: "ADEGHARAGBA",
    dateOfBirth: "2007-10-21",
    position: "Forward",
    pos: "FW",
    preferredFoot: "R",
    jerseyNumber: 37,
    height: "176",
    weight: "68",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 15,
    firstName: "OLAMILEKAN",
    lastName: "OLATUNJI",
    dateOfBirth: "2008-06-21",
    position: "Defender",
    pos: "RB",
    preferredFoot: "R",
    jerseyNumber: 2,
    height: "168",
    weight: "60",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 16,
    firstName: "OLUWASEYI",
    lastName: "OGUNNIYI",
    dateOfBirth: "2007-03-11",
    position: "Defender",
    pos: "RB",
    preferredFoot: "R",
    jerseyNumber: 13,
    height: "172",
    weight: "66",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 17,
    firstName: "OREOLUWA",
    lastName: "AGBENLA",
    dateOfBirth: "2008-12-07",
    position: "Midfielder",
    pos: "CM",
    preferredFoot: "L",
    jerseyNumber: 14,
    height: "173",
    weight: "62",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 18,
    firstName: "PETER",
    lastName: "ADEJIMI",
    dateOfBirth: "2007-05-29",
    position: "Forward",
    pos: "FW",
    preferredFoot: "R",
    jerseyNumber: 24,
    height: "165",
    weight: "56",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 19,
    firstName: "PRECIOUS",
    lastName: "OLANIYO",
    dateOfBirth: "2009-06-16",
    position: "Forward",
    pos: "FW",
    preferredFoot: "R",
    jerseyNumber: 33,
    height: "176.5",
    weight: "62",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 20,
    firstName: "PROMISE",
    lastName: "MELIGA",
    dateOfBirth: "2007-08-21",
    position: "Forward",
    pos: "FW",
    preferredFoot: "L",
    jerseyNumber: 11,
    height: "171",
    weight: "62",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 21,
    firstName: "RAWA",
    lastName: "MOHAMMED",
    dateOfBirth: "2007-10-28",
    position: "Midfielder",
    pos: "DM",
    preferredFoot: "L",
    jerseyNumber: 6,
    height: "183",
    weight: "74",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 22,
    firstName: "RIDWAN",
    lastName: "MOGAJI",
    dateOfBirth: "2007-02-12",
    position: "Forward",
    pos: "ST",
    preferredFoot: "R",
    jerseyNumber: 19,
    height: "173",
    weight: "68",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 23,
    firstName: "SAMUEL",
    lastName: "OKIKIOLA",
    dateOfBirth: "2007-04-03",
    position: "Forward",
    pos: "FW",
    preferredFoot: "R",
    jerseyNumber: 23,
    height: "170",
    weight: "58",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 24,
    firstName: "SODIQ",
    lastName: "LAWAL",
    dateOfBirth: "2008-01-14",
    position: "Defender",
    pos: "LB",
    preferredFoot: "L",
    jerseyNumber: 12,
    height: "178",
    weight: "63",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 25,
    firstName: "SUNDAY",
    lastName: "OGBONNAYA",
    dateOfBirth: "2007-10-26",
    position: "Forward",
    pos: "FW",
    preferredFoot: "R",
    jerseyNumber: 8,
    height: "168",
    weight: "63",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 26,
    firstName: "TAIWO",
    lastName: "COLE",
    dateOfBirth: "2007-12-19",
    position: "Midfielder",
    pos: "CM",
    preferredFoot: "L",
    jerseyNumber: 10,
    height: "179",
    weight: "70",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 27,
    firstName: "TOHEEB",
    lastName: "JIMOH",
    dateOfBirth: "2007-02-01",
    position: "Defender",
    pos: "CB",
    preferredFoot: "R",
    jerseyNumber: 5,
    height: "182",
    weight: "67",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 28,
    firstName: "TOHEEB",
    lastName: "ABIODUN",
    dateOfBirth: "2007-06-19",
    position: "Forward",
    pos: "ST",
    preferredFoot: "L",
    jerseyNumber: 16,
    height: "179",
    weight: "75",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 29,
    firstName: "VALENTINE",
    lastName: "NWEKE",
    dateOfBirth: "2007-02-14",
    position: "Midfielder",
    pos: "DM",
    preferredFoot: "R",
    jerseyNumber: 18,
    height: "184",
    weight: "80",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },
  {
    id: 30,
    firstName: "WARIS",
    lastName: "HASSAN",
    dateOfBirth: "2008-01-08",
    position: "Midfielder",
    pos: "DM",
    preferredFoot: "L",
    jerseyNumber: 28,
    height: "180.5",
    weight: "67",
    imageUrl:
      "https://backend.liverpoolfc.com/sites/default/files/styles/lg/public/2024-08/mohamed-salah-alternative-body-v2-2024.png?itok=VMLtOKVH",
  },

  // Continue for the rest of the players...
];
